/**
 * Minimal Web Push sender built on WebCrypto only, so it runs unchanged on
 * Deno Deploy and locally without dependencies.
 *
 * Implements the two RFCs a push service requires:
 * - RFC 8291: message encryption with the `aes128gcm` content encoding.
 * - RFC 8292: VAPID (a signed ES256 JWT in the Authorization header).
 *
 * The server holds one VAPID key pair (env: VAPID_PUBLIC_KEY /
 * VAPID_PRIVATE_KEY, generated by scripts/generate-vapid-keys.ts). Browsers
 * hand out a subscription (endpoint + p256dh + auth); `sendPushMessage`
 * encrypts a payload for that subscription and POSTs it to the endpoint.
 */

export type PushSubscriptionKeys = {
  /** Base64url, the subscriber's P-256 public key (65 bytes uncompressed). */
  p256dh: string;
  /** Base64url, the subscriber's 16 byte auth secret. */
  auth: string;
};

export type PushSubscriptionData = {
  endpoint: string;
  keys: PushSubscriptionKeys;
};

export type VapidKeys = {
  /** Base64url of the raw 65 byte uncompressed public key, as browsers expect it. */
  publicKey: string;
  /** ECDSA P-256 signing key. */
  privateKey: CryptoKey;
};

export type PushSendResult = {
  ok: boolean;
  status: number;
  /** The push service says the subscription no longer exists (404/410). */
  subscriptionGone: boolean;
  body: string;
};

export function base64UrlEncode(bytes: Uint8Array): string {
  let binary = "";
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

export function base64UrlDecode(value: string): Uint8Array<ArrayBuffer> {
  const base64 = value.replace(/-/g, "+").replace(/_/g, "/");
  const padded = base64 + "=".repeat((4 - (base64.length % 4)) % 4);
  const binary = atob(padded);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

function concatBytes(...parts: Uint8Array[]): Uint8Array<ArrayBuffer> {
  const total = parts.reduce((sum, part) => sum + part.length, 0);
  const out = new Uint8Array(total);
  let offset = 0;
  for (const part of parts) {
    out.set(part, offset);
    offset += part.length;
  }
  return out;
}

/**
 * Import the VAPID key pair from the raw base64url formats used by the
 * common tooling (`scripts/generate-vapid-keys.ts`, `npx web-push
 * generate-vapid-keys`): the public key is the 65 byte uncompressed EC point,
 * the private key the 32 byte scalar.
 */
export async function importVapidKeys(publicKeyB64: string, privateKeyB64: string): Promise<VapidKeys> {
  const publicBytes = base64UrlDecode(publicKeyB64);
  if (publicBytes.length !== 65 || publicBytes[0] !== 0x04) {
    throw new Error("VAPID public key must be a base64url encoded 65 byte uncompressed P-256 point");
  }
  const privateBytes = base64UrlDecode(privateKeyB64);
  if (privateBytes.length !== 32) {
    throw new Error("VAPID private key must be a base64url encoded 32 byte P-256 scalar");
  }

  const jwk: JsonWebKey = {
    kty: "EC",
    crv: "P-256",
    x: base64UrlEncode(publicBytes.slice(1, 33)),
    y: base64UrlEncode(publicBytes.slice(33, 65)),
    d: privateKeyB64,
  };

  const privateKey = await crypto.subtle.importKey("jwk", jwk, { name: "ECDSA", namedCurve: "P-256" }, false, [
    "sign",
  ]);

  return { publicKey: publicKeyB64, privateKey };
}

/** Build the `vapid t=<jwt>, k=<key>` Authorization header value (RFC 8292). */
export async function buildVapidAuthorization(
  endpoint: string,
  subject: string,
  vapid: VapidKeys,
): Promise<string> {
  const encoder = new TextEncoder();
  const header = base64UrlEncode(encoder.encode(JSON.stringify({ typ: "JWT", alg: "ES256" })));
  const claims = base64UrlEncode(
    encoder.encode(
      JSON.stringify({
        aud: new URL(endpoint).origin,
        exp: Math.floor(Date.now() / 1000) + 12 * 60 * 60,
        sub: subject,
      }),
    ),
  );

  const signingInput = `${header}.${claims}`;
  // WebCrypto returns the raw r||s signature, which is exactly the JWS ES256 format.
  const signature = await crypto.subtle.sign(
    { name: "ECDSA", hash: "SHA-256" },
    vapid.privateKey,
    encoder.encode(signingInput),
  );

  const jwt = `${signingInput}.${base64UrlEncode(new Uint8Array(signature))}`;
  return `vapid t=${jwt}, k=${vapid.publicKey}`;
}

async function hkdf(
  ikm: Uint8Array<ArrayBuffer>,
  salt: Uint8Array<ArrayBuffer>,
  info: Uint8Array<ArrayBuffer>,
  byteLength: number,
): Promise<Uint8Array<ArrayBuffer>> {
  const key = await crypto.subtle.importKey("raw", ikm, "HKDF", false, ["deriveBits"]);
  const bits = await crypto.subtle.deriveBits({ name: "HKDF", hash: "SHA-256", salt, info }, key, byteLength * 8);
  return new Uint8Array(bits);
}

/**
 * Encrypt a payload for a subscription with the `aes128gcm` scheme (RFC 8291).
 * Returns the full request body: the encryption header followed by the single
 * encrypted record.
 */
export async function encryptPushPayload(
  keys: PushSubscriptionKeys,
  plaintext: Uint8Array,
): Promise<Uint8Array<ArrayBuffer>> {
  const userAgentPublicBytes = base64UrlDecode(keys.p256dh);
  if (userAgentPublicBytes.length !== 65 || userAgentPublicBytes[0] !== 0x04) {
    throw new Error("Subscription p256dh key must be a 65 byte uncompressed P-256 point");
  }
  const authSecret = base64UrlDecode(keys.auth);
  if (authSecret.length !== 16) {
    throw new Error("Subscription auth secret must be 16 bytes");
  }

  const userAgentPublicKey = await crypto.subtle.importKey(
    "raw",
    userAgentPublicBytes,
    { name: "ECDH", namedCurve: "P-256" },
    false,
    [],
  );
  const applicationServerKeys = await crypto.subtle.generateKey({ name: "ECDH", namedCurve: "P-256" }, true, [
    "deriveBits",
  ]);
  const applicationServerPublicBytes = new Uint8Array(
    await crypto.subtle.exportKey("raw", applicationServerKeys.publicKey),
  );

  const ecdhSecret = new Uint8Array(
    await crypto.subtle.deriveBits(
      { name: "ECDH", public: userAgentPublicKey },
      applicationServerKeys.privateKey,
      256,
    ),
  );

  const encoder = new TextEncoder();
  // ikm = HKDF(salt=auth, ecdh_secret, "WebPush: info" || 0x00 || ua_public || as_public, 32)
  const keyInfo = concatBytes(
    encoder.encode("WebPush: info"),
    new Uint8Array([0]),
    userAgentPublicBytes,
    applicationServerPublicBytes,
  );
  const ikm = await hkdf(ecdhSecret, authSecret, keyInfo, 32);

  const salt = crypto.getRandomValues(new Uint8Array(16));
  const contentEncryptionKey = await hkdf(ikm, salt, encoder.encode("Content-Encoding: aes128gcm\0"), 16);
  const nonce = await hkdf(ikm, salt, encoder.encode("Content-Encoding: nonce\0"), 12);

  // A single record: plaintext || 0x02 (the last-record padding delimiter).
  const record = concatBytes(plaintext, new Uint8Array([2]));
  const aesKey = await crypto.subtle.importKey("raw", contentEncryptionKey, "AES-GCM", false, ["encrypt"]);
  const ciphertext = new Uint8Array(await crypto.subtle.encrypt({ name: "AES-GCM", iv: nonce }, aesKey, record));

  // Header: salt (16) || record size (4) || key id length (1) || key id (the server public key).
  const recordSize = new Uint8Array(4);
  new DataView(recordSize.buffer).setUint32(0, 4096);
  const header = concatBytes(
    salt,
    recordSize,
    new Uint8Array([applicationServerPublicBytes.length]),
    applicationServerPublicBytes,
  );

  return concatBytes(header, ciphertext);
}

/**
 * Encrypt and deliver one payload to one subscription. Never throws for
 * delivery failures — the result carries the status, and `subscriptionGone`
 * tells the caller to drop the subscription.
 */
export async function sendPushMessage(args: {
  subscription: PushSubscriptionData;
  payload: string;
  vapid: VapidKeys;
  /** Contact for the push service operator, e.g. "mailto:you@example.com". */
  subject: string;
  ttlSeconds: number;
  urgency?: "very-low" | "low" | "normal" | "high";
}): Promise<PushSendResult> {
  const { subscription, payload, vapid, subject, ttlSeconds, urgency } = args;

  const body = await encryptPushPayload(subscription.keys, new TextEncoder().encode(payload));
  const authorization = await buildVapidAuthorization(subscription.endpoint, subject, vapid);

  const response = await fetch(subscription.endpoint, {
    method: "POST",
    headers: {
      Authorization: authorization,
      TTL: String(ttlSeconds),
      "Content-Encoding": "aes128gcm",
      "Content-Type": "application/octet-stream",
      Urgency: urgency ?? "normal",
    },
    body,
    signal: AbortSignal.timeout(10_000),
  });

  const responseBody = await response.text().catch(() => "");
  return {
    ok: response.ok,
    status: response.status,
    subscriptionGone: response.status === 404 || response.status === 410,
    body: responseBody,
  };
}
